Template.qanda.helpers({
  candidateQuestions: function () {
    return [
      { 'questionStub' : 'Quality of Life',  'answer' : 'Coming soon...', 'question' : '1. What three things would you advocate for that would increase the quality of life for Hamiltonians, and attract new residents to the city?'},
      { 'questionStub' : 'Economy',  'answer' : 'Coming soon...', 'question' : '2. Hamilton has a tax base imbalance (77% residential vs. 23% commercial/industrial in 2013), coupled with an industrial vacancy rate of less than 2%. How will you overcome these challenges to grow the city’s economy and attract additional corporate investment?' }, 
      { 'questionStub' : 'Industry Clusters',  'answer' : 'Coming soon...', 'question' : '3. The City of Hamilton’s Economic Development division has identified several industry clusters with high potential (advanced manufacturing; agribusiness & food processing, clean tech; creative industries; and life sciences). What is the mayor’s role in attracting investment in these clusters?' },
      { 'questionStub' : 'Education & Youth',  'answer' : 'Coming soon...', 'question' : '4. Hamilton has some of the top post-secondary education institutions in Canada. What role would you play in the attraction, engagement and retention of youth in the city of Hamilton?'},
      { 'questionStub' : 'Red Tape',  'answer' : 'Coming soon...', 'question' : '5. Our members business ventures rely heavily on the ease with which their project applications are reviewed and processed by City staff; as well as the clarity and quality of information available to current and prospective business owners. Considering “government red tape” is a perennial election topic, what ideas and priorities do you have to foster more effective interaction between businesses and City Hall?'},
      { 'questionStub' : 'Business Community',  'answer' : 'Coming soon...', 'question' : '6. As Mayor, what steps will you take to improve and facilitate the voice of the business community with all levels of government?'}, 
      { 'questionStub' : 'Transportation',  'answer' : 'Coming soon...', 'question' : '7. As mayor what is your strategic vision for the future of Hamilton’s Transportation Infrastructure? This includes but is not limited to: The future of the Light Rail Transit initiative, Complete Streets conversion, Commercial freight infrastructure etc. '},
      { 'questionStub' : 'Industrial Development',  'answer' : 'Coming soon...', 'question' : '8. Hamilton has significant potential for industrial and commercial growth close to its transportation hubs, namely the Hamilton International Airport and the Hamilton Port Authority. What kind of development would you like to see around these hubs, especially the current and future brownfield vacancies at Hamilton’s Waterfront Industrial areas?'},
      { 'questionStub' : 'Housing Affordability',  'answer' : 'Coming soon...', 'question' : '9. The Hamilton commercial and residential real estate market is facing pressures such as limited land availability in the urban boundary and increasing land values, and affordability will become a greater challenge over the next few years. Furthermore, the expansion in scope and pricing of development application fees and development charges has put additional pressure on the real estate affordability. Lastly, 2015 will see a review of, among a number of other related plans, the Greenbelt, with an eye to modifying or expanding its limits.  What are your thoughts on ensuring that businesses and home buyers will continue to find affordability and choice in Hamilton?'},
      { 'questionStub' : 'Housing Opportunities',  'answer' : 'Coming soon...', 'question' : '10. Given Council’s adoption of the 10-year Housing and Homelessness Action Plan how would you advocate for increased housing opportunities for all Hamiltonians?'},
      { 'questionStub' : 'Land Transfer Tax',  'answer' : 'Coming soon...', 'question' : '11. New Research has found that, if enacted, the municipal land transfer tax in Hamilton will lead to the loss of $342 million in economic activity and a reduction of $176 million in GDP. If elected as Mayor, will you protect affordable home ownership and commit to not bringing a municipal land transfer tax to Hamilton?'},
      { 'questionStub' : 'Downtown Revitalization',  'answer' : 'Coming soon...', 'question' : '12. How do you envision the role of a revitalizing downtown core as a key pillar of Hamilton’s economic future and what policy goals will you champion to further facilitate it?'}
    ]
  },
  brianAnswers: function () {
    return [
      { 'answer' : '1. My platform has identified 5 key themes I believe contribute to the quality of life for Hamiltonians, both separately and together. They are: Stronger Neighbourhoods, Smarter Growth, Healthier Environment, More Open Government, More Jobs. For example, stronger neighbourhoods are one of the results of smarter growth (better not just bigger), which protects our environment (built and natural), and produces more jobs (for long term residents, newcomers, and new graduates). Within those, top three things include: Waterfront Development; Safer Neighbourhood Streets and Sidewalks; and Improving Hamilton’s Image.' },
      { 'answer' : '2. My focus is to find new revenue from new sources. Smarter growth helps to deliver on that. Currently, we have lower commercial office tax rates. I want to leverage that competitive advantage to attract more mid sized, job-rich sectors to Hamilton. My proposed Open For Business Contract will help get those businesses open faster. Increasing our commercial and retail tax base is key to keeping the lid on residential property taxes. ' }, 
      { 'answer' : '3. I see the Mayor’s role as one of leader. The Mayor needs to foster great relationships at all levels of government and to use those relationships to communicate a clear, compelling vision for Hamilton. But, as has been pointed out by many, the Mayor has one vote. That means that we attract investment to our City be working together as a leadership team. There is a ton of strength around the Council table. I plan to enlist those strengths to achieve success. I’ve talked about this before as “focused collaboration”. It’s the only way to be successful.' },
      { 'answer' : '4. Again, this speaks to my More Jobs theme. If we don’t focus our efforts as a City on attracting job-rich sectors, our graduates from our 3 post-secondary institutions have to look elsewhere for work. That’s not good for them, neither as individuals or as members of families, nor for the future of our City. I believe McMaster University Downtown campus is a big win, helping to get students out of the “Westdale Bubble” and deeply into the heart of our city. ' },
      { 'answer' : '5. I’ve been pretty clear this is a message I’ve heard loud and clear from businesspeople I’ve met on my 100 Day Neighbourhood Tour, as well as from businesses with whom I worked as Councillor for Ward 1. That’s why I have proposed an Open For Business Contract between the City of Hamilton and investors, whether small business entrepreneurs or large scale developers and investors. We don’t have to break the rules to follow the rules faster. We need a mutually beneficial and clear contract that respects the needs and realities of both parties, with dates, deliverables, expectations, etc. As a City, we need to do a better job of this. Currently, our internal culture and procedures are making life too difficult and too expensive for people who want to invest in our City.' },
      { 'answer' : '6. I believe great relationships with all levels of government include all partners - Council, senior staff, businesspeople, community leaders, and so on. For too many years, we’ve had very spotty and very unclear communication with other levels of government. That has to change immediately. I will ensure I understand what business is looking for and what they’re expectations of government are to realize their goals. I suspect we’ll agree on many things, and perhaps disagree on a few things, but true partners get past those kinds of disagreements through dialogue. Fighting is good for the media, but a very poor way of achieving progress.' }, 
      { 'answer' : '7. Efficient goods movement is critical. The new Council Walkability Plan, combined with CarShare, BikeShare, the Shifting Gears Cycling Plan, and the Rapid Ready Plan are designed to shift to a stronger active transportation focus. The more people move to other modes, the more space on the roads for moving goods and creating commerce.  I articulated a 4-part Transit City Plan in May. I’ve also posted a video that explains my plan. As is the case with all municipalities, it relies on partnering with the provincial government. The 4 parts are: 1. Increase Neighbourhood Bus Service. 2. Enhance the Upper James A-Line Express on the mountain. 3. Implement LRT on the King Street B-Line. 4. Provide online, real-time, mobile data for HSR buses.' },
      { 'answer' : '8. Brownfield redevelopment is a particularly relevant challenge and opportunity for Hamilton. Our industrial past helped build Hamilton, but it has also left us with an abundance of lands that will need to be remediated before they can once again be productive. What we must all remember is that these brownfields are almost always in already serviced parts of the City. Water lines, sewers, electricity, roads, fire hydrants, etc. already exist. Tapping back into them makes sense on so many levels, including smarter growth. The issue is one of remediation. That will take further innovation and cooperation, not only with potential investors, but with all levels of government. The fact is, it makes good business and social sense to figure this out. I think we all have to agree that the changes we’ve made along our waterfront have been good for all Hamiltonians. Great planning, great cooperation, focused on achieving a great vision are all within our grasp.  John C. Munro Airport has great potential in growing our already successful freight business, bolstered by employment lands in the AEGD. Additional passenger opportunities must be explored. Part of this must be investigating potential partnerships with the GTAA.' },
      { 'answer' : '9. While land values have been rising within a Hamilton context, they remain affordable for those seeking real estate from the GTA. Our industrial land supply has never been better with the Red Hill Business Park being serviced now, and the 555 ha Airport Employment Growth Area to come in the near future, along with the West Hamilton Innovation District, and lands along the busiest port in the Great Lakes, Hamilton Harbour. The city has  a good residential land supply which will improve with increasing the focus on efficiently using intensification lands within the existing urban boundary. The Elfrida expansion area has been identified for a future urban boundary expansion.' },
      { 'answer' : '10. As President of City Housing Hamilton over the past decade I‘ve led the creation of hundreds of new affordable housing units across the City, with additional units planned over the next 3 years. Hamilton needs a tripartite agreement with the Federal and Provincial governments in order to successfully implement this necessary plan, achieved through and aggressive government relations strategy. The City needs to invite partnership with the private sector to include affordable housing units in their for-profit developments by taking advantage of Section 37 of the Planning Act, allowing additional density in exchange for public benefit.' },
      { 'answer' : '11. I have no intention of introducing a land transfer tax to Hamilton.' },
      { 'answer' : '12. We’ve already seen great progress downtown through Council’s ambitious grants and loans program and a huge boost from private sector investment. Commercial, retail, residential, arts, etc. The Chamber’s own members are behind some of these changes. Just look at the potential for the Royal Connaught. One city block that’s already serviced by water, sewage, electricity, transit, police, fire department, EMS,etc. that will become the home to over 1300 people, and to new businesses. Half of them will be located in two historic buildings. That’s new property taxes from 700 residential units, and likely a few dozen new businesses. All downtown. All on one city block. The implications to businesses beyond that single city block are significant too. The implications to new residential units beyond that single city block are also compelling. I will focus on bringing more office employment to downtown, renovating existing stock and encouraging new builds. I will also support a stronger link to the waterfront. My belief is that a healthier environment includes built and natural environment. I love to see creative adaptive reuse of our built heritage. Entrepreneurs have proven there is a market for such projects, both residential and commercial. I want to encourage more of that, as well as new builds where we have empty lots at the moment. We’re seeing progress that is tangible, profitable, and sustainable. For businesspeople and for residents, that’s a great combination.' }
    ]
  }
}); 

Template.qanda.rendered = function () {

    var splitURL = document.URL.split('#');
    var targetDiv = splitURL[1];
    console.log(targetDiv);

    $('html, body').animate({
        scrollTop: $("#" + targetDiv + "").offset().top
    }, 1000);
};
