Template.qanda.helpers({
  candidateQuestions: function () {
    return [
      { 'questionStub' : 'Quality of Life',  'answer' : 'Coming soon...', 'question' : '1. What three things would you advocate for that would increase the quality of life for Hamiltonians, and attract new residents to the city?'},
      { 'questionStub' : 'Economy',  'answer' : 'Coming soon...', 'question' : '2. Hamilton has a tax base imbalance (77% residential vs. 23% commercial/industrial in 2013), coupled with an industrial vacancy rate of less than 2%. How will you overcome these challenges to grow the city’s economy and attract additional corporate investment?' }, 
      { 'questionStub' : 'Industry Clusters',  'answer' : 'Coming soon...', 'question' : '3. The City of Hamilton’s Economic Development division has identified several industry clusters with high potential (advanced manufacturing; agribusiness & food processing, clean tech; creative industries; and life sciences). What is the mayor’s role in attracting investment in these clusters?' },
      { 'questionStub' : 'Education & Youth',  'answer' : 'Coming soon...', 'question' : '4. Hamilton has some of the top post-secondary education institutions in Canada. What role would you play in the attraction, engagement and retention of youth in the city of Hamilton?'},
      { 'questionStub' : 'Red Tape',  'answer' : 'Coming soon...', 'question' : '5. Our members business ventures rely heavily on the ease with which their project applications are reviewed and processed by City staff; as well as the clarity and quality of information available to current and prospective business owners. Considering “government red tape” is a perennial election topic, what ideas and priorities do you have to foster more effective interaction between businesses and City Hall?'},
      { 'questionStub' : 'Business Community',  'answer' : 'Coming soon...', 'question' : '6. As Mayor, what steps will you take to improve and facilitate the voice of the business community with all levels of government?'}, 
      { 'questionStub' : 'Transportation',  'answer' : 'Coming soon...', 'question' : '7. As mayor what is your strategic vision for the future of Hamilton’s Transportation Infrastructure? This includes but is not limited to: The future of the Light Rail Transit initiative, Complete Streets conversion, Commercial freight infrastructure etc. '},
      { 'questionStub' : 'Industrial Development',  'answer' : 'Coming soon...', 'question' : '8. Hamilton has significant potential for industrial and commercial growth close to its transportation hubs, namely the Hamilton International Airport and the Hamilton Port Authority. What kind of development would you like to see around these hubs, especially the current and future brownfield vacancies at Hamilton’s Waterfront Industrial areas?'},
      { 'questionStub' : 'Housing Affordability',  'answer' : 'Coming soon...', 'question' : '9. The Hamilton commercial and residential real estate market is facing pressures such as limited land availability in the urban boundary and increasing land values, and affordability will become a greater challenge over the next few years. Furthermore, the expansion in scope and pricing of development application fees and development charges has put additional pressure on the real estate affordability. Lastly, 2015 will see a review of, among a number of other related plans, the Greenbelt, with an eye to modifying or expanding its limits.  What are your thoughts on ensuring that businesses and home buyers will continue to find affordability and choice in Hamilton?'},
      { 'questionStub' : 'Housing Opportunities',  'answer' : 'Coming soon...', 'question' : '10. Given Council’s adoption of the 10-year Housing and Homelessness Action Plan how would you advocate for increased housing opportunities for all Hamiltonians?'},
      { 'questionStub' : 'Land Transfer Tax',  'answer' : 'Coming soon...', 'question' : '11. New Research has found that, if enacted, the municipal land transfer tax in Hamilton will lead to the loss of $342 million in economic activity and a reduction of $176 million in GDP. If elected as Mayor, will you protect affordable home ownership and commit to not bringing a municipal land transfer tax to Hamilton?'},
      { 'questionStub' : 'Downtown Revitalization',  'answer' : 'Coming soon...', 'question' : '12. How do you envision the role of a revitalizing downtown core as a key pillar of Hamilton’s economic future and what policy goals will you champion to further facilitate it?'}
    ]
  },
  brianAnswers: function () {
    return [
      { 'answer' : '1. My platform has identified 5 key themes I believe contribute to the quality of life for Hamiltonians, both separately and together. They are: Stronger Neighbourhoods, Smarter Growth, Healthier Environment, More Open Government, More Jobs. For example, stronger neighbourhoods are one of the results of smarter growth (better not just bigger), which protects our environment (built and natural), and produces more jobs (for long term residents, newcomers, and new graduates). Within those, top three things include: Waterfront Development; Safer Neighbourhood Streets and Sidewalks; and Improving Hamilton’s Image.' },
      { 'answer' : '2. My focus is to find new revenue from new sources. Smarter growth helps to deliver on that. Currently, we have lower commercial office tax rates. I want to leverage that competitive advantage to attract more mid sized, job-rich sectors to Hamilton. My proposed Open For Business Contract will help get those businesses open faster. Increasing our commercial and retail tax base is key to keeping the lid on residential property taxes. ' }, 
      { 'answer' : '3. I see the Mayor’s role as one of leader. The Mayor needs to foster great relationships at all levels of government and to use those relationships to communicate a clear, compelling vision for Hamilton. But, as has been pointed out by many, the Mayor has one vote. That means that we attract investment to our City be working together as a leadership team. There is a ton of strength around the Council table. I plan to enlist those strengths to achieve success. I’ve talked about this before as “focused collaboration”. It’s the only way to be successful.' },
      { 'answer' : '4. Again, this speaks to my More Jobs theme. If we don’t focus our efforts as a City on attracting job-rich sectors, our graduates from our 3 post-secondary institutions have to look elsewhere for work. That’s not good for them, neither as individuals or as members of families, nor for the future of our City. I believe McMaster University Downtown campus is a big win, helping to get students out of the “Westdale Bubble” and deeply into the heart of our city. ' },
      { 'answer' : '5. I’ve been pretty clear this is a message I’ve heard loud and clear from businesspeople I’ve met on my 100 Day Neighbourhood Tour, as well as from businesses with whom I worked as Councillor for Ward 1. That’s why I have proposed an Open For Business Contract between the City of Hamilton and investors, whether small business entrepreneurs or large scale developers and investors. We don’t have to break the rules to follow the rules faster. We need a mutually beneficial and clear contract that respects the needs and realities of both parties, with dates, deliverables, expectations, etc. As a City, we need to do a better job of this. Currently, our internal culture and procedures are making life too difficult and too expensive for people who want to invest in our City.' },
      { 'answer' : '6. I believe great relationships with all levels of government include all partners - Council, senior staff, businesspeople, community leaders, and so on. For too many years, we’ve had very spotty and very unclear communication with other levels of government. That has to change immediately. I will ensure I understand what business is looking for and what they’re expectations of government are to realize their goals. I suspect we’ll agree on many things, and perhaps disagree on a few things, but true partners get past those kinds of disagreements through dialogue. Fighting is good for the media, but a very poor way of achieving progress.' }, 
      { 'answer' : '7. Efficient goods movement is critical. The new Council Walkability Plan, combined with CarShare, BikeShare, the Shifting Gears Cycling Plan, and the Rapid Ready Plan are designed to shift to a stronger active transportation focus. The more people move to other modes, the more space on the roads for moving goods and creating commerce.  I articulated a 4-part Transit City Plan in May. I’ve also posted a video that explains my plan. As is the case with all municipalities, it relies on partnering with the provincial government. The 4 parts are: 1. Increase Neighbourhood Bus Service. 2. Enhance the Upper James A-Line Express on the mountain. 3. Implement LRT on the King Street B-Line. 4. Provide online, real-time, mobile data for HSR buses.' },
      { 'answer' : '8. Brownfield redevelopment is a particularly relevant challenge and opportunity for Hamilton. Our industrial past helped build Hamilton, but it has also left us with an abundance of lands that will need to be remediated before they can once again be productive. What we must all remember is that these brownfields are almost always in already serviced parts of the City. Water lines, sewers, electricity, roads, fire hydrants, etc. already exist. Tapping back into them makes sense on so many levels, including smarter growth. The issue is one of remediation. That will take further innovation and cooperation, not only with potential investors, but with all levels of government. The fact is, it makes good business and social sense to figure this out. I think we all have to agree that the changes we’ve made along our waterfront have been good for all Hamiltonians. Great planning, great cooperation, focused on achieving a great vision are all within our grasp.  John C. Munro Airport has great potential in growing our already successful freight business, bolstered by employment lands in the AEGD. Additional passenger opportunities must be explored. Part of this must be investigating potential partnerships with the GTAA.' },
      { 'answer' : '9. While land values have been rising within a Hamilton context, they remain affordable for those seeking real estate from the GTA. Our industrial land supply has never been better with the Red Hill Business Park being serviced now, and the 555 ha Airport Employment Growth Area to come in the near future, along with the West Hamilton Innovation District, and lands along the busiest port in the Great Lakes, Hamilton Harbour. The city has  a good residential land supply which will improve with increasing the focus on efficiently using intensification lands within the existing urban boundary. The Elfrida expansion area has been identified for a future urban boundary expansion.' },
      { 'answer' : '10. As President of City Housing Hamilton over the past decade I‘ve led the creation of hundreds of new affordable housing units across the City, with additional units planned over the next 3 years. Hamilton needs a tripartite agreement with the Federal and Provincial governments in order to successfully implement this necessary plan, achieved through and aggressive government relations strategy. The City needs to invite partnership with the private sector to include affordable housing units in their for-profit developments by taking advantage of Section 37 of the Planning Act, allowing additional density in exchange for public benefit.' },
      { 'answer' : '11. I have no intention of introducing a land transfer tax to Hamilton.' },
      { 'answer' : '12. We’ve already seen great progress downtown through Council’s ambitious grants and loans program and a huge boost from private sector investment. Commercial, retail, residential, arts, etc. The Chamber’s own members are behind some of these changes. Just look at the potential for the Royal Connaught. One city block that’s already serviced by water, sewage, electricity, transit, police, fire department, EMS,etc. that will become the home to over 1300 people, and to new businesses. Half of them will be located in two historic buildings. That’s new property taxes from 700 residential units, and likely a few dozen new businesses. All downtown. All on one city block. The implications to businesses beyond that single city block are significant too. The implications to new residential units beyond that single city block are also compelling. I will focus on bringing more office employment to downtown, renovating existing stock and encouraging new builds. I will also support a stronger link to the waterfront. My belief is that a healthier environment includes built and natural environment. I love to see creative adaptive reuse of our built heritage. Entrepreneurs have proven there is a market for such projects, both residential and commercial. I want to encourage more of that, as well as new builds where we have empty lots at the moment. We’re seeing progress that is tangible, profitable, and sustainable. For businesspeople and for residents, that’s a great combination.' }
    ]
  },
  fredAnswers: function () {
    return [
      { 'answer' : '1. Take decisive action to reduce poverty and increase safe, affordable housing• Work with community partners to explore new apprenticeship and cooperative programs in the business and agri-business sectors to create opportunities for newcomers through education and job skills training• Work with public and private sector partners to attract more businesses to Hamilton that will create more jobs and opportunities. To ensure success, I am committed to implementing a seamless process to encourage more businesses to establish roots in Hamilton to create new opportunity and a strong local economy' },
      { 'answer' : '2. As a major Canadian city, Hamilton relies heavily on economic development as one of its key drivers. While jobs, income and sustainable taxes are of equal importance, the broader focus must include advanced manufacturing, creative industries, agriculture and food processing, clean technology and local innovation, life sciences and transportation/goods movement. As mayor, I am committed to work hard with community, business and industry leaders to provide diverse economic opportunities in Hamilton that will result in greater investment, increased revenues and more employment opportunities for the people of Hamilton. I am also committed to bring a renewed focus on growing the commercial/industrial tax base to assist in reducing residential taxes.' }, 
      { 'answer' : '3. One of the mayor’s main functions is to deliver progressive leadership based on a successful, collaborative approach with Council colleagues, City staff and members of the community in every corner of Hamilton. Together, we can embrace a new future for our great city, working towards making Hamilton a more livable community by building a green economy, implementing solutions to end poverty and homelessness and by investing in innovation and creativity to improve our quality of life. The mayor must be prepared to be the city’s ambassador for progress, growth and change for the better.' },
      { 'answer' : '4. Many post-secondary graduates want to live, work and play in clean, safe, modern communities brimming with opportunity. Competitive employment opportunities, environmental sustainability and long term potential for growth are all attractive components in keeping young graduates living, working and, eventually, raising their own families in Hamilton. I am committed to maintaining and further strengthening the City’s partnerships with McMaster, Mohawk and Redeemer and to establish a seamless approach that will encourage both elected officials and City staff to become civically and socially engaged together with our fine educational institutions. Post-secondary expertise and innovation can assist the City with new approaches to local innovation, economic development and help to improve living conditions – especially in the city’s poor areas. As Mayor, I will do everything possible to facilitate positive, effective partnerships and to help keep graduates engaged and interested from first year to post-graduate levels. Together, we can establish a collective, personal commitment to becoming agents of social change, while increasing public goodwill between the municipality and post-secondary institutions. In addition, I will work together with community organizations, post-secondary partners and Council colleagues to develop a framework for a made-in-Hamilton Equity and Inclusion Lens to be used in creating municipal policy. This will help establish Hamilton as a world-class municipality that can provide opportunities for everyone.' },
      { 'answer' : '5. It’s time to rethink how we do business at City Hall. That starts with a smarter, more collaborative, consumer and business friendly city government. Transparency, accountability and open, two-way communication with all Hamiltonians will bring about a new and improved approach to how we do business. There must be a renewed commitment for municipal staff and elected representatives to work together effectively to ensure an open, transparent and responsible city government. I am committed to working with Council, staff and the business community to ensure the implementation of a seamless process to encourage more businesses to plant roots in Hamilton, leading to the creation of new opportunity and a strong local economy. The first step to success in this area is to consult with the business community about how best we can improve upon our current processes and the elimination of both real and perceived “red tape” issues at City Hall.' },
      { 'answer' : '6. To be clear, the mayor’s role is to represent the voices of all Hamiltonians – including the business sector – with other levels of government. As the fifth largest city in Ontario and the 10thwe need a strong, experienced voice at that table to get Hamilton back on the radar with the provincial and federal governments to secure the financial investment we deserve. I will do everything possible to reinvigorate our partnerships with governments and the private sector to make sure Hamilton is getting its fair share of investment dollars to build a more livable community with revitalize energy, new ambition and a renewed sense of pride. The first step to success will be for the mayor and members of Council to work with municipal staff to build a comprehensive government relations framework designed to bring together appropriate and resources, and strengthen relationships with business and industry, education, and health and wellness sectors. Together, we will create:− Municipal investment strategies for infrastructure− Program and service initiatives for short, medium and longer term objectives− Foster new investment strategies that will contribute to an overall increase in economic prosperity and sustainability for Hamilton, the province and our country.' }, 
      { 'answer' : '7. Transportation infrastructure in Hamilton is important to our community and our citizens. Modern public transit has become a key staple for any modern city. With Hamilton uniquely situated as the gateway to all points north, south, east and west, we can create a modern transportation system for Hamilton. This includes protecting and enhancing the current level of bus transit service and to add more buses to address scheduling shortfalls (if any) and to expand service to those areas that are currently under-serviced. • We must also undertake a review of the recommendations contained in the City of Hamilton’s Rapid Ready report (February 2013), and focus on short term implementation.• Establish a community forum with citizens from all parts of the city through equitable representation (similar to the consensus forum on area rating) to assess all public transportation options at public meetings held throughout the entire city as frequently as necessary to inform themselves and obtain substantial community feedback. • Charge the forum to access all available evidence from appropriate City staff reports, Metrolinx and third party studies on public transit options for Hamilton including Light Rail Transit, Bus Rapid Transit (BRT), the need for additional roads, and expanding the existing transportation  largest city in Canada, we already have an important seat at the table. But system • Make recommendations to City Council on the future direction of modern public transportation for the city of Hamilton based on their research, evidence based information and community feedback. • While there has been solid public support for LRT, there are people in Hamilton who have real concerns about the cost of LRT and its potential impact on the city. We need to talk about the benefits and the real return on investment from modern public transit and most importantly, we need to address the concerns of people. Community engagement and meaningful dialogue are the best option to stimulate the conversation going and the only way to reach consensus on this important issue.• I have remained supportive of LRT as a viable public transit option for Hamilton because it has the potential to attract millions of outside investment dollars into our community (as evidenced in Kitchener-Waterloo, Ottawa, Toronto and Calgary) resulting in thousands of new employment opportunities, growth and re-urbanization, and huge potential for economic uplift and additional revenue for the entire city. ' },
      { 'answer' : '8. We need to maximize the value of the Airport Employment District shovel ready lands. It cannot be a question of brownfield versus greenfield development. We need to focus there on businesses and industry that offers employment providing good and decent living wages that people can raise a family on. Not on row after row of warehousing. We should be working aggressively with the Hamilton Port Authority on identifying priority lands taking into account the need for increased shipping capacity for the future. We need to be creative and innovative in developing brownfields given the greater costs involved. Remediating brownfields should be an equal priority with greenfield development. It is realistically however a much bigger challenge.' },
      { 'answer' : '9. There must be ongoing consultation with the real estate industry on the development charges by law and the cities future needs and how we balance that with the needs of the industry and the cities future service delivery demands. Although we can and should be more efficient, the city of Hamilton biggest issue is not spending but revenue; especially lost revenue over the years in the commercial industrial‎ sector that has put increasing pressure on the residential taxpayer. The more new business and growth we can inspire on existing infrastructure is a logical growth and revenue benefit for the city. However longer term needs must also be considered so there will be a continuing need to develop green field growth within the urban boundary. I do not support an urban boundary expansion for residential growth at this time and I think it is appropriate to review the green belt legislation. Protecting our farm land is an important part of our agri-business strategy that can continue to be a job producing economic engine for our city. Reviewing the green belt legislation will inform us as to how it has worked where it has not and to make sensible recommendation on whether or not adjustments need to be made‎.The real estate development industry should continue to provide a range of options for our city that helps fulfill our long term‎ housing needs at all levels of affordability.' },
      { 'answer' : '10. The Housing and Homelessness Action Plan is clear about the importance of the role of advocacy .The first thing would be to advocate to our senior levels of government to partner with the City to address our housing issues - by which I mean pay their share so it does not fall on the local taxpayer alone. The Province and the Federal government long ago vacated the affordable housing field and while they have returned to a degree it has not been nearly enough. Affordable housing makes economic sense. The business case for affordable housing needs to be placed before all three levels of government as an issue that requires our immediate attention as a priority in our community. The execution of the Housing and Homelessness Action Plan requires clear leadership from both council and the Mayor’s office.' },
      { 'answer' : '11. Coming Soon' },
      { 'answer' : '12. Coming Soon' }
    ]
  }
}); 

Template.qanda.rendered = function () {

    var splitURL = document.URL.split('#');
    var targetDiv = splitURL[1];
    console.log(targetDiv);

    $('html, body').animate({
        scrollTop: $("#" + targetDiv + "").offset().top
    }, 1000);
};
